import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MSWInitializer } from "@/mocks/initialize";
import { Toaster } from "@/components/ui/sonner";
import NextAuthSessionProvider from "@/components/providers/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Initialize MSW in development environment */}
        {process.env.NODE_ENV === "development" && <MSWInitializer />}
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
